print ("Hello, World")
print ("Hello, this is Khaliyl")
print ("Problen 2")
print ("Problem 1")
print ("Problem Solved")
print ("solving documentation problem")
print ("This is also an option for my group member to solve: or you can pick this")
